version: '3.9'
services:
  app:
    image: node:16
    working_dir: /app
    ports:
      - "3001:3000"
      - "6007:6006"
    volumes:
      - ./src:/app
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
    # command: sh -c "npm run dev"
    # command: npm run dev
    tty: true